
trigger:
- main

pool:
  name: 'test-project' # Use your self-hosted agent pool

variables:
  IMAGE_NAME: 'nginx-custom'
  REGISTRY: 'acr0987.azurecr.io'
  KUBECONFIG: '/home/learning/.kube/config'
  ACR_USERName: 'acr0987' 


stages:
- stage: PullAndPush
  jobs:
  - job: PullTagPush
    steps:
    - script: |
        docker login $(REGISTRY) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
        echo "Pulling official NGINX image"
        docker pull nginx:latest

        echo "Tagging image with ACR registry"
        docker tag nginx:latest $(REGISTRY)/$(IMAGE_NAME):latest

        echo "Logging in to ACR"
        az acr login --name acr0987

        echo "Pushing image to ACR"
        docker push $(REGISTRY)/$(IMAGE_NAME):latest
      displayName: 'Pull, Tag & Push NGINX to ACR'

- stage: Deploy
  jobs:
  - job: DeployToMinikube
    steps:
    - script: |
        echo "Setting Minikube context"
        kubectl config use-context minikube
        kubectl get nodes
      displayName: 'Set Minikube Context'

    - script: |
        echo "Creating deployment YAML"

        cat <<EOF > nginx-deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: $(REGISTRY)/$(IMAGE_NAME):latest
                ports:
                - containerPort: 80
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx-service
        spec:
          type: NodePort
          selector:
            app: nginx
          ports:
          - port: 80
            targetPort: 80
            nodePort: 30080
        EOF
      displayName: 'Generate NGINX Deployment YAML'

    - script: |
        echo "Deploying NGINX to Minikube"
        kubectl apply -f nginx-deployment.yaml
        kubectl rollout status deployment/nginx
        kubectl get svc nginx-service
      displayName: 'Deploy to Minikube'