trigger:
- main

pool:
  name: 'test-project' # Use your self-hosted agent pool

variables:
  IMAGE_NAME: 'myapp'
  REGISTRY: 'acr0987.azurecr.io'
  KUBECONFIG: '/home/learning/.kube/config'

stages:
- stage: Build
  jobs:
  - job: BuildPush
    steps:
    - checkout: self

    - task: Docker@2
      inputs:
        containerRegistry: 'acr'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

- stage: Deploy
  jobs:
  - job: DeployToMinikube
    steps:
    - script: |
        echo "Using Minikube context"
        kubectl config use-context minikube
        kubectl get nodes
      displayName: 'Set Minikube Context'

    - script: |
        echo "Deploying to Minikube"
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
      displayName: 'Deploy to Minikube'